zero-to-mastery/ascii-art-2022

- webapp/.gitignore
- webapp/README.md
- webapp/ascii_art.py
- webapp/make_art.py
- webapp/requirements.txt
- webapp/templates/ascii.html
- webapp/templates/base.html
- webapp/templates/upload.html
Create a tiny Flask web app that uses the given example code to print the ASCII art on a webpage.
> Initial commit for the ASCII Art Web App

- community-version.py
Hello, 
I have added the ability to choose different CHAR_SETs (different characters to represent the art with), using two ways:
1. Previously made CHAR_SETs, including the one that was there in the example file, and a one that I have included
2. The user enters a list of characters that he/she wants to use.
To use, simply select the number of the CHAR_SET from the terminal after naming the image file path, or pass a list including the characters that you want to use.
**Note:** If the user does not select anything, the default (original) CHAR_SET will be used.
I have different CHAR_SETs and they work just fine, though I am being sceptical that some characters might not work. 
Also, I have added some error handling.
> Add the ability to choose from different CHAR_SETS

- community-version.py
A call to this function should be used in place of `print(image_ascii)` on line 56 in `make_art.py`. It will randomly generate 4 loading sentences that pull from 2 lists of Verbs and Nouns to hype up the user before displaying their ASCII art. This was fun, thanks for making it available!
> Add function that will display randomized tech-related hype

- community-version.py
In case you forget to specify a path for file, the code will avoid Index Error and ask you for File Path as an Input.
> Sys index error solved.

- community-version.py
So, a function to inverse the color of the provided image has been added to the community version. I also took some time to add an argument parser to make the cli more flexible when adding new features.
> inverse colors & arg parser

- community-version.py
simple fix for the issue(#5) where a custom list of character was not being properly process.
> fix CHAR_SET invalid subarray issue

- README.md
- community-version.py
- requirements.txt
This PR adds [rich](https://github.com/Textualize/rich) as a dependency and showcases just a part of its powers in the hype part.
> Use the "rich" library to make the hype more hype

- webapp/templates/upload.html
just added simple css to the webapp - upload.html ,free feel to edit it and suggest the colors in discord channel ,will edit the other pages soon and add a nav bar
> added html to webapp upload.html

- community-version.py
Till now, the users of this program cant store ASCII art. After this users can store/save the ASCII art result to a txt file by passing a simple optional argument _--store filename.txt_.  This also supports the other destination path.
> Now user can store/save the ASCII art to a txt file

- community_version.py
Hi,
Added option to save file in SVG format.
It will open the file in web browser as well.
Please review and let me know if need any changes.
Regards
Avinash
> Added option to save file in SVG format and open in web browser

- GUI/community-version.py
- requirements.txt
Added welcome text to be displayed when write_to_txtfile method is invoked.
> add welcome text in output file

- ASCII_Video_Inside_Terminal/README.md
- ASCII_Video_Inside_Terminal/main.py
- requirements.txt
Added a programme that can be used to view video inside a Terminal.
> Added ASCII video inside Terminal Feature.😊

- community_version.py
Hi, 
I have added color replacement for image. Please check
> Replacing image with new color yellow

- community_version.py
"Welcome to ASCII ART Generator" message added.
> Welcome message added

- community_version.py
Added the single ASCII change withdefault preset change
> Added single ASCII conversion using existing default preset

- webapp/static/color-picker.js
> Fix color assignment not done properly.

- community_version.py
Hi,
I have added a drawing effect with multiple colours option.
Regards
Avinash
> Added drawing with different colour option

- GUI/community-version.py
- GUI/community_version.py
- GUI/desktop_version.py
I have tried to stick to original solutions (although might have changed little parts, mostly by removing not working/not used code). Main change is refactoring to use classes. 
Unfortunately I had to change filename (it was not compliant with python import requirements), so the comparison might be more difficult.
> Refactor community_version.py 

- API/README.md
Fixed typo in API/Readme.md file
> fixed typo in API/Readme.md

- community_version.py
This is my first pull request here and I added a few new verbs and nouns to the dummy hype loading bar to add a bit more flavor. 😄
> Added 10 new verbs and 6 new nouns to hype

- community_version.py
I made some small improvements to the language output in the console
> Minor improvements to language output in console

- FEATURES.md
Please feel free to recheck if it seems wrong. HACKTOBERFEST-ACCEPTED
> Added the supported IMG files extensions.
